### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**
_Changelog_

* Translations updated
* Translation system expanded
* -webkit-background-clip > background-clip
* Changed > Updated (Sounds better 😉)
* USERS_IS_ADMIN > USER_IS_ADMIN (singular, not plural)

### CODE REVIEW

**Comment by ToBiDi0410** [comment]
Thanks for taking the time to improve this plugin.
**I will check out the changes as soon as possible**

**Comment by Justman10000** [comment]
> Thanks for taking the time to improve this plugin. **I will check out the changes as soon as possible**

Okay, I tested everything locally, it works!

**Comment by ToBiDi0410** [comment]
Checked everything. Should work out fine.
Thanks for your contribution.

**Comment by Justman10000** [comment]
> Checked everything. Should work out fine. Thanks for your contribution.

Ein paar Vorschläge noch:

- Player bans (permanent or temporary)
- World creation (with all the options as if creating a world locally in the Minecraft client)
- Deleting worlds
- Regenerate worlds (with custom or random seed)
- List entities when clicking on a group (if the group Chicken exists, and the number is as example 14, you can click on it to see all the Chickens, including their life points, position, etc)
- Add under world tab that can set all the rules of the respective world
- Expand editor to support ALL file types
- Restart plugins (instead of stopping and starting)

**Comment by Justman10000** [comment]
A few more suggestions:

- Player bans (permanent or temporary)
- World creation (with all the options as if creating a world locally in the Minecraft client)
- Deleting worlds
- Regenerate worlds (with custom or random seed)
- List entities when clicking on a group (if the group Chicken exists, and the number is as example 14, you can click on it to see all the Chickens, including their life points, position, etc)
- Add under world tab that can set all the rules of the respective world
- Expand editor to support ALL file types
- Restart plugins (instead of stopping and starting)

**Comment by ToBiDi0410** [comment]
> A few more suggestions:
> 
> * Player bans (permanent or temporary)
> * World creation (with all the options as if creating a world locally in the Minecraft client)
> * Deleting worlds
> * Regenerate worlds (with custom or random seed)
> * List entities when clicking on a group (if the group Chicken exists, and the number is as example 14, you can click on it to see all the Chickens, including their life points, position, etc)
> * Add under world tab that can set all the rules of the respective world
> * Expand editor to support ALL file types
> * Restart plugins (instead of stopping and starting)

SpigotDash as it is currently deprecated. I'm not working on it anymore.
But I'm working on a new Version/Plugin that might feature these things when released.
If you want to, you can implement these features, but this probably isn't worth it when a new plugin will come out eventually.

**Comment by Justman10000** [comment]
> > A few more suggestions:
> > 
> > * Player bans (permanent or temporary)
> > * World creation (with all the options as if creating a world locally in the Minecraft client)
> > * Deleting worlds
> > * Regenerate worlds (with custom or random seed)
> > * List entities when clicking on a group (if the group Chicken exists, and the number is as example 14, you can click on it to see all the Chickens, including their life points, position, etc)
> > * Add under world tab that can set all the rules of the respective world
> > * Expand editor to support ALL file types
> > * Restart plugins (instead of stopping and starting)
> 
> SpigotDash as it is currently deprecated. I'm not working on it anymore. But I'm working on a new Version/Plugin that might feature these things when released. If you want to, you can implement these features, but this probably isn't worth it when a new plugin will come out eventually.

Why a new plugin when you can extend the existing one?

**Comment by ToBiDi0410** [comment]
> Why a new plugin when you can extend the existing one?

The current one is not like I would do it today. Expanding is hard and takes much time because of some things that are written up very poorly. In addition to that, the Web interface is built with plain JavaScript. Today, I would use Vue or some other frameworks for dynamic data serving.

I have not really announced that I'm working on a new plugin because I don't know when it's going to be finished. But exactly at this moment I was working on it :)

**Comment by Justman10000** [comment]
Then why did you do it in JavaScript back then? And not immediately in Vue?

**Comment by ToBiDi0410** [comment]
> Then why did you do it in JavaScript back then? And not immediately in Vue?

Because I wasn't really confident with Vue back then and this project started only with the 4 graphs on the main page. No other features were planned.

**Comment by Justman10000** [comment]
> > Then why did you do it in JavaScript back then? And not immediately in Vue?
> 
> Because I wasn't really confident with Vue back then and this project started only with the 4 graphs on the main page. No other features were planned.

So, the new plugin will come in Vue?

**Comment by ToBiDi0410** [comment]
> So, the new plugin will come in Vue?

Yes

**Comment by Justman10000** [comment]
And what's so bad about pure JavaScript? Does it work?

**Comment by ToBiDi0410** [comment]
> And what's so bad about pure JavaScript? Does it work?

Are you trolling me?
Please read the notice in the README File.
I can't provide more information than I gave you.
_Please remind that this is my opinion!_

**Pull request merged**
